### ISSUE TITLE
Data structures for message passing

### ISSUE THREAD

**Issue by nicorsm** [simoneapp/S3-16-simone#21]
## Subscription

A person in the group (the "host") creates a common channel with friends invited to the match. This channel will serve to know which friends are available to join the match. A possible structure of the subscription message sent from the host could be:

`Channel name: presence-a53722e2-25be-4176-a876-9386f75f2f4e`

```
{
    "match":"a53722e2-25be-4176-a876-9386f75f2f4e", 
    "sender":"10291230129039123"
}
```

Friends save the sender Facebook ID and will reply with a message like this:
```
{
     "match":"a53722e2-25be-4176-a876-9386f75f2f4e",
     "recipient":"98903545049324",
     "available":true
}
```

## Game message passing

After all the friends subscribed to the `presence-` channel, the host creates three other channels, called `match-a53722e2-25be-4176-a876-9386f75f2f4e-with-<RECIPIENT_FB_ID>`.

### Multiplayer by turn

The exchanged messages will be structured like this:

#### Sender

```
{
     "sequence":"r,g,b,y,y,b,g,r",
     "turn":4
}
```

#### Receiver

```
{
     "turn":5
}
```

### Multiplayer nearby

The exchanged messages will be structured like this:

#### Sender

```
{
     "expectedColour":"r"
}
```

#### Receiver

```
{
     "correct":true
}
```

**Comment by giacomobartoli** [comment]
We decided to move to a cloud solution in order to maintain data synced amongst devices, handling scenarious such as absence of connectivity and other issues coming from distributed systems.
Next step: migrate from Pubnub (message passing) to Firebase (cloud server)
